import { Dataset } from './types';

export const mockDatasets: Dataset[] = [
  {
    id: '1',
    title: 'Global Life Expectancy Trends (2000-2023)',
    description: 'Comprehensive dataset tracking life expectancy at birth across 195 countries. Includes breakdown by gender and socioeconomic status.',
    source: 'World Health Organization (WHO)',
    sourceType: 'International',
    category: 'Demographics',
    region: 'Global',
    dateUpdated: '2023-11-15',
    format: ['CSV', 'JSON'],
    size: '24 MB',
    tags: ['longevity', 'global health', 'trends'],
    downloads: 1240,
    featured: true,
    sampleData: [
      { name: '2000', value: 67 },
      { name: '2005', value: 69 },
      { name: '2010', value: 71 },
      { name: '2015', value: 72 },
      { name: '2020', value: 73 },
    ]
  },
  {
    id: '2',
    title: 'US State-Level Opioid Prescription Rates',
    description: 'Annual opioid dispensing rates per 100 persons by state. Data aggregated from IQVIA Xponent.',
    source: 'CDC',
    sourceType: 'Federal',
    category: 'Population Health',
    region: 'North America',
    dateUpdated: '2024-01-10',
    format: ['CSV', 'XLSX'],
    size: '1.2 MB',
    tags: ['opioids', 'prescriptions', 'substance abuse'],
    downloads: 850,
    featured: true,
    sampleData: [
      { name: 'Alabama', value: 98 },
      { name: 'Arkansas', value: 93 },
      { name: 'Tennessee', value: 87 },
      { name: 'Mississippi', value: 85 },
      { name: 'Louisiana', value: 79 },
    ]
  },
  {
    id: '3',
    title: 'Indiana Hospital Bed Capacity & Utilization',
    description: 'Daily census of staffed hospital beds, ICU availability, and ventilator usage across Indiana healthcare facilities.',
    source: 'Indiana Department of Health',
    sourceType: 'State',
    category: 'Medical Capabilities',
    region: 'Indiana',
    dateUpdated: '2024-03-01',
    format: ['CSV', 'API'],
    size: '5.5 MB',
    tags: ['hospitals', 'capacity', 'emergency response'],
    downloads: 420,
    featured: false,
    sampleData: [
      { name: 'ICU', value: 78 },
      { name: 'Non-ICU', value: 65 },
      { name: 'Pediatric', value: 45 },
      { name: 'ER', value: 82 },
    ]
  },
  {
    id: '4',
    title: 'COVID-19 Policy Response Tracker',
    description: 'Database of government policy responses to COVID-19 (stringency index, containment, economic support) for 180+ countries.',
    source: 'Oxford Blavatnik School',
    sourceType: 'International',
    category: 'Policies',
    region: 'Global',
    dateUpdated: '2023-12-01',
    format: ['CSV'],
    size: '15 MB',
    tags: ['covid-19', 'policy', 'pandemic'],
    downloads: 3100,
    featured: true,
    sampleData: [
      { name: 'USA', value: 65 },
      { name: 'China', value: 78 },
      { name: 'Italy', value: 55 },
      { name: 'Sweden', value: 30 },
    ]
  },
  {
    id: '5',
    title: 'Sub-Saharan Africa Maternal Mortality Rates',
    description: 'Longitudinal study of maternal mortality ratios (per 100,000 live births) in 48 Sub-Saharan African nations.',
    source: 'UNICEF',
    sourceType: 'International',
    category: 'Diseases',
    region: 'Africa',
    dateUpdated: '2023-09-20',
    format: ['JSON', 'CSV'],
    size: '3 MB',
    tags: ['maternal health', 'mortality', 'women'],
    downloads: 560,
    sampleData: [
      { name: 'Nigeria', value: 917 },
      { name: 'Chad', value: 1140 },
      { name: 'Sierra Leone', value: 1120 },
      { name: 'Somalia', value: 829 },
    ]
  },
  {
    id: '6',
    title: 'National Health Interview Survey (NHIS) 2022',
    description: 'Cross-sectional household interview survey monitoring the health of the United States population.',
    source: 'NCHS',
    sourceType: 'Federal',
    category: 'Demographics',
    region: 'North America',
    dateUpdated: '2023-08-15',
    format: ['CSV', 'SAS'],
    size: '120 MB',
    tags: ['survey', 'population', 'disability'],
    downloads: 2100,
  },
  {
    id: '7',
    title: 'EU Environmental Noise Exposure',
    description: 'Data on exposure to environmental noise from road, rail, air traffic, and industry in European urban areas.',
    source: 'European Environment Agency',
    sourceType: 'International',
    category: 'Population Health',
    region: 'Europe',
    dateUpdated: '2024-01-05',
    format: ['SHP', 'CSV'],
    size: '450 MB',
    tags: ['environment', 'pollution', 'urban'],
    downloads: 340,
  },
  {
    id: '8',
    title: 'California Immunization Registry Data',
    description: 'Vaccination coverage rates for kindergarteners by school and county in California.',
    source: 'California HHS',
    sourceType: 'State',
    category: 'Diseases',
    region: 'California',
    dateUpdated: '2023-10-10',
    format: ['CSV'],
    size: '2.1 MB',
    tags: ['vaccines', 'schools', 'children'],
    downloads: 670,
  },
  {
    id: '9',
    title: 'Mental Health Facilities in Australia',
    description: 'Location and capacity of specialized mental health care facilities across Australian states and territories.',
    source: 'AIHW',
    sourceType: 'International',
    category: 'Medical Capabilities',
    region: 'Oceania',
    dateUpdated: '2023-11-28',
    format: ['JSON', 'XML'],
    size: '800 KB',
    tags: ['mental health', 'facilities', 'access'],
    downloads: 290,
    sampleData: [
      { name: 'NSW', value: 45 },
      { name: 'VIC', value: 38 },
      { name: 'QLD', value: 30 },
      { name: 'WA', value: 22 },
    ]
  },
  {
    id: '10',
    title: 'Global Diabetes Prevalence',
    description: 'Estimated age-standardized diabetes prevalence in adults aged 20-79 years by country.',
    source: 'IDF Diabetes Atlas',
    sourceType: 'International',
    category: 'Diseases',
    region: 'Global',
    dateUpdated: '2024-02-14',
    format: ['CSV'],
    size: '1.8 MB',
    tags: ['diabetes', 'chronic disease', 'global'],
    downloads: 1500,
  },
  {
    id: '11',
    title: 'New York State Medicaid Spending',
    description: 'Detailed breakdown of Medicaid expenditures by service category and county in NY.',
    source: 'NY Dept of Health',
    sourceType: 'State',
    category: 'Policies',
    region: 'New York',
    dateUpdated: '2024-01-22',
    format: ['CSV', 'XLSX'],
    size: '18 MB',
    tags: ['finance', 'medicaid', 'insurance'],
    downloads: 410,
  },
  {
    id: '12',
    title: 'Air Quality Index (AQI) Historical Data - Delhi',
    description: 'Hourly PM2.5 and PM10 measurements for monitoring stations across Delhi, India.',
    source: 'CPCB India',
    sourceType: 'International',
    category: 'Population Health',
    region: 'Asia',
    dateUpdated: '2024-03-05',
    format: ['CSV'],
    size: '64 MB',
    tags: ['air quality', 'pollution', 'environment'],
    downloads: 890,
    sampleData: [
      { name: 'Jan', value: 350 },
      { name: 'Feb', value: 280 },
      { name: 'Mar', value: 210 },
      { name: 'Apr', value: 180 },
    ]
  }
];

export const CATEGORIES = ['Policies', 'Demographics', 'Diseases', 'Medical Capabilities', 'Population Health'];
export const SOURCE_TYPES = ['State', 'Federal', 'International'];
export const REGIONS = ['Global', 'North America', 'Europe', 'Asia', 'Africa', 'South America', 'Oceania', 'Indiana', 'California', 'New York'];
